const fs = require("fs");

const meta = [
  {
    Name: "Hypeculture Tie-Dye T-Shirt",
    Image:
      "https://drive.google.com/file/d/1jylJhDUOv1MRpRrstpFyXSrSeMVPb1Tm/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Purple Tie-Dye",
    Design: "Hypeculture Tie-Dye",
    Type: "T-Shirt",
    Quantity: 5,
  },
  {
    Name: "Hypeculture Tie-Dye Hoodie",
    Image:
      "https://drive.google.com/file/d/1noCMNQ4GY4QbCZCObcQWztLgIFygjJTq/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Magenta Tie-Dye",
    Design: "Hypeculture Tie-Dye",
    Type: "Hoodie",
    Quantity: 7,
  },
  {
    Name: "Snake Hoodie 3",
    Image:
      "https://drive.google.com/file/d/1n1aGCRM6Dvdxk58d0uGTe-DtwN06zQkZ/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Snake",
    Type: "Hoodie",
    Quantity: 5,
  },
  {
    Name: "Snake Hoodie 2",
    Image:
      "https://drive.google.com/file/d/1FRhuFI0SBvmrHMbfyT3lT-TwU3wZfD_1/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Snake",
    Type: "Hoodie",
    Quantity: 5,
  },
  {
    Name: "Snake Hoodie",
    Image:
      "https://drive.google.com/file/d/1kuiED16gJDl68LVCpuS7wOYLQuu34LHj/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Snake",
    Type: "Hoodie",
    Quantity: 5,
  },
  {
    Name: "Chain Hoodie 3",
    Image:
      "https://drive.google.com/file/d/1gq3GZvuJW6z11iqYrIvsroSbEOntMGgL/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Chain",
    Type: "Hoodie",
    Quantity: 5,
  },
  {
    Name: "Chain Hoodie",
    Image:
      "https://drive.google.com/file/d/11cpjtVObTIEdEKuc6RtKbzXnLNObDdUH/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Chain",
    Type: "Hoodie",
    Quantity: 5,
  },
  {
    Name: "Chain Hoodie 2",
    Image:
      "https://drive.google.com/file/d/1k3dviK9iGeMy0X4Are5QGeupxabd0r53/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Chain",
    Type: "Hoodie",
    Quantity: 5,
  },
  {
    Name: "Snake Sweatshirt",
    Image:
      "https://drive.google.com/file/d/1gBVFczBHohS3wIrrWFbuzcWE1t3Eyl07/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Snake",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Snake Sweatshirt 1",
    Image:
      "https://drive.google.com/file/d/1i6J11bIQl9liiRpbYw0kLAsmOOw4NiUM/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture Snake",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Snake Sweatshirt 2",
    Image:
      "https://drive.google.com/file/d/1U4b0bEsa-TqGFMc_efKO_eNmTsAk3FRI/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Snake",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Snake Sweatshirt 4",
    Image:
      "https://drive.google.com/file/d/1NnFWyyfh3c6lLkjKGmg6wLOU36H4Ffbc/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Snake",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Chain Sweatshirt 1",
    Image:
      "https://drive.google.com/file/d/1Ag4wUTP17IkcAGTG-ES26FNYS_2p8asU/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Chain",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Chain Sweatshirt 2",
    Image:
      "https://drive.google.com/file/d/1zha2g1doPph8VHkzpHjRpOSGqSeiDlfc/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture Chain",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Chain Sweatshirt 3",
    Image:
      "https://drive.google.com/file/d/1qsPjp6Gy3u32nk6L55ZEHZCYi1oJswZL/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Chain",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Chain Sweatshirt",
    Image:
      "https://drive.google.com/file/d/1J8GtehvSMn0-8Gi8dqKYtufFCMGHfsx-/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Chain",
    Type: "Sweatshirt",
    Quantity: 5,
  },
  {
    Name: "Snake T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1EdiIUTj9rcK-YILUMcDxDOiM6iM8tZbz/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Snake",
    Type: "T-Shirt",
    Quantity: 5,
  },
  {
    Name: "Snake T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/1CKsL2UiRWAIRkq0lZAkrQ3yuodZwu8aq/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Snake",
    Type: "T-Shirt",
    Quantity: 5,
  },
  {
    Name: "Snake T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/1260zTzwx3CaEqjDB05dzoSPMsU1cPyKg/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Military Green",
    Design: "HypeCulture Snake",
    Type: "T-Shirt",
    Quantity: 5,
  },
  {
    Name: "Snake T-Shirt",
    Image:
      "https://drive.google.com/file/d/1m7YgSL4D-Xzch35r-x55DMq1uWRkU66J/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Snake",
    Type: "T-Shirt",
    Quantity: 5,
  },
  {
    Name: "Original Tye-Die 3",
    Image:
      "https://drive.google.com/file/d/1UfuC61Z4O3axBiz9Xz_wsGbuOLeKVKrH/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Rainbow Tie-Dye",
    Design: "HypeCulture Original Tye-Die",
    Type: "T-Shirt",
    Quantity: 5,
  },
  {
    Name: "Original Tye-Die 1",
    Image:
      "https://drive.google.com/file/d/1Kyq2lXOakbgtfe05FxX-oMq1wiUVcGbY/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Blue Tie-Dye",
    Design: "HypeCulture Original Tye-Die",
    Type: "T-Shirt",
    Quantity: 7,
  },
  {
    Name: "Original Tye-Die 4",
    Image:
      "https://drive.google.com/file/d/1tbrLm5VGEhKdzTGMd4geHHkRq5JXEc3M/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Black Tie-Dye",
    Design: "HypeCulture Original Tye-Die",
    Type: "T-Shirt",
    Quantity: 7,
  },
  {
    Name: "Original Tye-Die",
    Image:
      "https://drive.google.com/file/d/1h1HQ5ehyuft_b-hZBsqmtqNayqZ_A1p2/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Light Pastel Tie-Dye",
    Design: "HypeCulture Original Tye-Die",
    Type: "T-Shirt",
    Quantity: 5,
  },
  {
    Name: "HypeCulture G BackPack 1",
    Image:
      "https://drive.google.com/file/d/1EscdpLlYYqk89oJeK9Uv7BD_Tnf9Vvst/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Purple",
    Design: "HypeCulture G BackPack",
    Type: "BackPack",
    Quantity: 5,
  },
  {
    Name: "HypeCulture G BackPack 2",
    Image:
      "https://drive.google.com/file/d/19zrXhJ-33x_oUjWcsZDQ_2pc5RJYifE5/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Yellow",
    Design: "HypeCulture G BackPack",
    Type: "BackPack",
    Quantity: 5,
  },
  {
    Name: "HypeCulture G BackPack 3",
    Image:
      "https://drive.google.com/file/d/1wIfk-Hmt9QDrAKT_Q4x45RxUIDeD-D1V/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture G BackPack",
    Type: "BackPack",
    Quantity: 5,
  },
  {
    Name: "HypeCulture G Sneakers",
    Image:
      "https://drive.google.com/file/d/1zdGtZVdcqKVRgHpqYCs44tOrrJSo3alS/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "Black/White",
    Design: "HypeCulture G Sneakers",
    Type: "Sneakers",
    Quantity: 7,
  },
  {
    Name: "Water Bottle",
    Image:
      "https://drive.google.com/file/d/1N98UMoh5bNugUri1pO75l4svVqMl7P3f/view?usp=sharing",
    Rarity: "Genesis",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Water Bottle",
    Type: "Water Bottle",
    Quantity: 5,
  },
  {
    Name: "Hypeculte BackPack",
    Image:
      "https://drive.google.com/file/d/1b16DmQS_LmlwyTqJwvp5Sz7jGqWVccwg/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Black",
    Design: "Hypeculte BackPack",
    Type: "BackPack",
    Quantity: 23,
  },
  {
    Name: "Hypeculte BackPack White",
    Image:
      "https://drive.google.com/file/d/1yjsJp6CvsmGRDp5KB4I7wlzXEECJ5g2w/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "White",
    Design: "Hypeculte BackPack",
    Type: "BackPack",
    Quantity: 23,
  },
  {
    Name: "Hypeculture Beanie",
    Image:
      "https://drive.google.com/file/d/1dScFzk616yzc_O7Jt2lusdhEmWtK1T0l/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Pink Tie-Dye",
    Design: "Hypeculture Tie-Dye",
    Type: "Beanie",
    Quantity: 23,
  },
  {
    Name: "Hypeculture Black Hoodie",
    Image:
      "https://drive.google.com/file/d/1YzinysEiD6rPO1KqmvMW-rlBaN-Fi2mF/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture",
    Type: "Hoodie",
    Quantity: 23,
  },
  {
    Name: "Hodl Long T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1wgzvJNxEVFeBVYaE6MSrr_THSfj2JuqZ/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Military Green",
    Design: "HypeCulture Hodl",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Hodl Long T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1phvW-L3I7fKO8jUutYFKyliWyW76Ai9d/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Beige",
    Design: "HypeCulture Hodl",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Hodl Long T-Shirt 6",
    Image:
      "https://drive.google.com/file/d/1eI1-aNVEYz9JkO4unXbtixTrwhqhDqkP/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Hodl",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Hodl Long T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/1_pPIX0STtsSG_KDXM9qPhmnGne-mDSCm/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Hodl",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Hodl Long T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/1T5AcZvMjoYRgnMa_wm95VrbU0iaDPOAM/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Teal",
    Design: "HypeCulture Hodl",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Hodl Long T-Shirt",
    Image:
      "https://drive.google.com/file/d/116hD6LKH5W1MbzGPAXw5R9Kky_WUwuOk/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Hodl",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Flower Long T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/1jQGga_PUU-HBVt5o6Xr0IWXMi1iAT7wW/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Military Green",
    Design: "HypeCulture Flower",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Flower Long T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1FWPdUeO4i_Kbm0N67DD2GeDJXcxdNx2n/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Beige",
    Design: "HypeCulture Flower",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Flower Long T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/1u9BX6PuCeEL76asMoJazUew-qOZapiH6/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Flower",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Flower Long T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/1mAIuqLAOjS6N9ipQth7aksrpwLGykg0O/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Flower",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Flower Long T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1sdLBz86jcuGc8b9E31al3K3WQHHJe3-h/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Teal",
    Design: "HypeCulture Flower",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Flower Long T-Shirt",
    Image:
      "https://drive.google.com/file/d/1f1Yk3Mv6ZSQkcpCEi_IuPmMDysXwmXhY/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Flower",
    Type: "Long T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Pump Dump T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1A4hVcFLLDOLX73A3xcbESRBHtsnGnvmv/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Dark Blue",
    Design: "HypeCulture Dump",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Pump Dump T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/1D_54FRocntmXAsGyCregnpg1YGQj5riM/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Green",
    Design: "HypeCulture Dump",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Pump Dump T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/1JmyY_Uc9GlTseZ7aeQgLDAJ2ywbwdXU7/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Dump",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Pump Dump T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/18HB39tH2A8GioY5at_ZhhdRFUmiAEGBa/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Purple",
    Design: "HypeCulture Dump",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Pump Dump T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1_9DRgNcNylFbgTYpqD7cYteLSjA-bUlf/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Dump",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "Pump Dump T-Shirt",
    Image:
      "https://drive.google.com/file/d/1ksu0PWHEZcyuOZ4j2bMkiBq-ZXyEolcO/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Dump",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 1",
    Image:
      "https://drive.google.com/file/d/1uoVbo45XIyTf6LBvsUbScL4ke3FGnxvV/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 2",
    Image:
      "https://drive.google.com/file/d/1wwc2mLtdaxnTqUXwJe5SGozf4gFYMTjx/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Dark Blue",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 3",
    Image:
      "https://drive.google.com/file/d/1ECLGFSJaPIvJBU7fu6aPMzlLQdMsywqG/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 4",
    Image:
      "https://drive.google.com/file/d/16f5u4AfpPyDNCtliTxmpViGasKm9tIMm/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 5",
    Image:
      "https://drive.google.com/file/d/1IbtpFhoukKQZJurObcXhEGgdmWAsm7nb/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Mauve",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 6",
    Image:
      "https://drive.google.com/file/d/1kYqkiejx77TtODhTSqM4J7WMUspiPraD/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Granate",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 7",
    Image:
      "https://drive.google.com/file/d/1Tqlqb34gmcIw_EPE3Pl-7Y97-eRQH9aU/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 8",
    Image:
      "https://drive.google.com/file/d/1cJkLGNCyPFo2c0s-2AZkAqTMrfzkGDsr/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt 0",
    Image:
      "https://drive.google.com/file/d/1VbfUGgz8egIF37Wx-OzhbKHpwsRdqqAr/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "bitcoin t-shirt",
    Image:
      "https://drive.google.com/file/d/1mCnc-h055-vEXSPisBZfOupVotQyacSJ/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Sky Blue",
    Design: "HypeCulture Bitcoin",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "hash rate t-shirt 1",
    Image:
      "https://drive.google.com/file/d/1ZT0XCTBzU11z_0l8kry2nQ-MeIP-nX2u/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Hash Rate",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "hash rate t-shirt 2",
    Image:
      "https://drive.google.com/file/d/14Taoft_BgBK_2csSTzI7PGnWsnUO8Ibn/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Hash Rate",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "hash rate t-shirt 3",
    Image:
      "https://drive.google.com/file/d/1vujNeSZiymcgOE5fE4yUMyr5bnN7Rcix/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Hash Rate",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "hash rate t-shirt 4",
    Image:
      "https://drive.google.com/file/d/1U5b6nqfaOYV9b2lWnv3VLGfYwyxOZQiU/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Hash Rate",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "hash rate t-shirt 6",
    Image:
      "https://drive.google.com/file/d/1Iu1z_7FidYCZWCN3Y0ATlhiJ0T6mUwCJ/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Granate",
    Design: "HypeCulture Hash Rate",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "hash rate t-shirt 0",
    Image:
      "https://drive.google.com/file/d/1bMgtCfYPMCD6YQqspN0wPkJbobDAa2da/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Hash Rate",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "hash rate t-shirt",
    Image:
      "https://drive.google.com/file/d/1OC_nlZxzPokF0aPyCq2pqCCuhBQIDhSD/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Hash Rate",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 1",
    Image:
      "https://drive.google.com/file/d/1bEiONFL3nehtdhA6hPwNN1g0DXE9WLXI/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Dark Blue",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 2",
    Image:
      "https://drive.google.com/file/d/1vdFLzv9P-zHLbwAWdcmXyXRPOX9FrLme/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 3",
    Image:
      "https://drive.google.com/file/d/1Ed-8AvlbHsnZ0PzOjdXvWPcxuitPTZ3r/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Purple",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 4",
    Image:
      "https://drive.google.com/file/d/10g6I4IVudJn_1qcKAsPKDxMgkMQwD0Oh/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Granate",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 5",
    Image:
      "https://drive.google.com/file/d/10J0ORbCtuxvzKkT9s9faM92b2w5lmWY8/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 6",
    Image:
      "https://drive.google.com/file/d/1lX0PS1jBjPijIOloxDvzol9BBmHgAtcG/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Green",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 7",
    Image:
      "https://drive.google.com/file/d/1AHXZFqGeE2pANK5gYmTLQLs36FI-fz2b/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Clay",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 8",
    Image:
      "https://drive.google.com/file/d/1Z6gfn1IhwV3s_LOv3JUm9BnWM65_ri4e/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Dark Grey",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 9",
    Image:
      "https://drive.google.com/file/d/1arvqTYH60kObid-tBIVW-n3pf3pEg46m/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt 0",
    Image:
      "https://drive.google.com/file/d/1dduBf6_cEoSfs-HldNiyz9BBxpLg_eLI/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "To the moon T-shirt",
    Image:
      "https://drive.google.com/file/d/1-eXNchKhKMtiCL6SAWFfyJMo8pt6mTb_/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture To The Moon",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1xf5dQuTRicTtloUJ0U5DFXt0eYUdnSG-/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "White",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/1PIQiRspj0MeZvyrOnuH8GoZAqmI9sJvI/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Dark Blue",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/1haSI3ceZaLBVI_3R9mh1abZUG57VUR7I/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Teal",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/14-ejNJ4EOIR6rYKAX67kfiO0Xhpq3p6m/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/17d9IMo6pLoGgKqkDddBN0uPHURHAXxM5/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Purple",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt 6",
    Image:
      "https://drive.google.com/file/d/1c4MA-pRsN8_SCO5zOLeRBXiVZsOMYuRy/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt 7",
    Image:
      "https://drive.google.com/file/d/1bQKtkD5lYpZ1IKpm4rPrJZ7jhGVAdaVX/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypHodl T-Shirt",
    Image:
      "https://drive.google.com/file/d/1auQaeYaGjvZDqV8y2d4TvS-ufTod-5wf/view?usp=sharing",
    Rarity: "Legendary",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture HypHodl",
    Type: "T-Shirt",
    Quantity: 23,
  },
  {
    Name: "HypeCulture Black Sneakers",
    Image:
      "https://drive.google.com/file/d/1Vilbk4gNnHhxlLwAGpWLidRwhFt7ej3M/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Sneakers",
    Type: "Sneakers",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Gold T-Shirt",
    Image:
      "https://drive.google.com/file/d/1c93ZmyxwbqQ8NDVMbgu8hyLCFH_JrgTq/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Gold",
    Type: "T-Shirt",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Wrecked Hoodie White",
    Image:
      "https://drive.google.com/file/d/1Uxi5dFRQHfRsGFRSPxC92FwSWnN7fZpl/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Wrecked",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Wrecked Hoodie Grey",
    Image:
      "https://drive.google.com/file/d/1omK1gDVsdnmSAFxQ9hLCcAdkzPV_7qct/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Wrecked",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Wrecked Blue",
    Image:
      "https://drive.google.com/file/d/1iQg8_RoWcZmtrbl7M67ARRuIcQt3hPRA/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Wrecked",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Wrecked Hoodie Pink",
    Image:
      "https://drive.google.com/file/d/1zhYxaNJPsqpDf51I7sLDME0KmAuRu2KO/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Wrecked",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture F Dip Hoodie Light Grey",
    Image:
      "https://drive.google.com/file/d/1tGN1hNipXxWU0rWMxSW090oTK3ZrBjG9/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Light Grey",
    Design: "HypeCulture F* Dip",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture F Dip Hoodie Dark Grey",
    Image:
      "https://drive.google.com/file/d/1H4gaViajsy8ac-48YFO4vwkV9Z1agMUV/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Dark Grey",
    Design: "HypeCulture F* Dip",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture F Dip Hoodie Blue",
    Image:
      "https://drive.google.com/file/d/1JIFMyhlYw5Ww_yrMcJS-Q7YppC9DFObS/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture F* Dip",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture F Dip Hoodie Black",
    Image:
      "https://drive.google.com/file/d/1nbB7B6k-2CDlcVqs_SmgXjgVT5WbI0fU/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture F* Dip",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture NFT Hoodie Light Grey",
    Image:
      "https://drive.google.com/file/d/1ikjgFA2R374Z5PT6mT_SqaXOUjxRrMyW/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Light Grey",
    Design: "HypeCulture NFT",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture NFT Hoodie Dark Grey",
    Image:
      "https://drive.google.com/file/d/1tUvqCGFYmEb0mTAJj_FhHn8zkVsO-w6x/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Dark Grey",
    Design: "HypeCulture NFT",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture NFT Hoodie Blue",
    Image:
      "https://drive.google.com/file/d/1TzFphUUukxiLHrtZ9PQlhSEQmUd8PILX/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture NFT",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "Hypeculture NFT Hoodie White",
    Image:
      "https://drive.google.com/file/d/1DGw36TSvUqysYpIqd2iIcJB5Dt2IS3Wl/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "White",
    Design: "HypeCulture NFT",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Stablecoin Hoodie Black",
    Image:
      "https://drive.google.com/file/d/1j94WXAXMkPaUv9kKvd3LhCIAVd53K6zT/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Stablecoin",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Stablecoin Hoodie Blue",
    Image:
      "https://drive.google.com/file/d/1kI3Uz1Bx-IXjgDSnPyLEMSsomJcodbJ2/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Stablecoin",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Stablecoin Hoodie L Grey",
    Image:
      "https://drive.google.com/file/d/1FxmssTjkLqZKc-N6aU31XWqkUCPXPCGZ/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Light Grey",
    Design: "HypeCulture Stablecoin",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Stablecoin Hoodie D Grey",
    Image:
      "https://drive.google.com/file/d/1cZgUIGlCuY-GtaKeyfgh1WPwyAyRZCUn/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Dark Grey",
    Design: "HypeCulture Stablecoin",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Token Hoodie White",
    Image:
      "https://drive.google.com/file/d/1YxZ0DcQrqZtokwIbE4_hwzcYFE4zbfJ5/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Token",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Token Hoodie Blue",
    Image:
      "https://drive.google.com/file/d/119oD50ysSDigTw5C53gCc83VS2uAUm03/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Token",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Token Hoodie L Grey",
    Image:
      "https://drive.google.com/file/d/1ogOPlTAs7lur8mrPp1vYLLB3COOmc4P9/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Light Grey",
    Design: "HypeCulture Token",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Token Hoodie D Grey",
    Image:
      "https://drive.google.com/file/d/1E6XwVyE21wNHDymwHCD396DIh_l_3pgA/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Dark Grey",
    Design: "HypeCulture Token",
    Type: "Hoodie",
    Quantity: 10,
  },
  {
    Name: "duffle bag 2",
    Image:
      "https://drive.google.com/file/d/1YK0gdEweRqGzqkhq-0Eh-9sntG5kUbdR/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture Duffle Bag",
    Type: "Duffle Bag",
    Quantity: 10,
  },
  {
    Name: "duffle bag 3",
    Image:
      "https://drive.google.com/file/d/1VKSGXqzdbJ8p9j0Zbi6NKPkJVNEQ4s09/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Duffle Bag",
    Type: "Duffle Bag",
    Quantity: 10,
  },
  {
    Name: "duffle bag 1",
    Image:
      "https://drive.google.com/file/d/1r_ZXggAhPyVGPE4XyKH5wiaroOXIJFp2/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Yellow",
    Design: "HypeCulture Duffle Bag",
    Type: "Duffle Bag",
    Quantity: 10,
  },
  {
    Name: "duffle bag",
    Image:
      "https://drive.google.com/file/d/1BdZTbMTePsdSKeZCVMiHbGBDAETmdpmE/view?usp=sharing",
    Rarity: "Mythic",
    Season: 1,
    Color: "Maroon",
    Design: "HypeCulture Duffle Bag",
    Type: "Duffle Bag",
    Quantity: 10,
  },
  {
    Name: "HypeCulture Tie-Dye Hat",
    Image:
      "https://drive.google.com/file/d/1Kh-xm7P6IiBaUIVLr3Q4pKGtJUElOcuj/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Green Tie-Dye",
    Design: "HypeCulture Tie-Dye Hat",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "HypeCulture Bucket Hat",
    Image:
      "https://drive.google.com/file/d/12WNWCRQb3KS9FyCh-d2Z8xal8dyidA0f/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Blue Purple Tie-Dye",
    Design: "HypeCulture Tie-Dye Bucket Hat",
    Type: "Bucket Hat",
    Quantity: 29,
  },
  {
    Name: "Buy the f dip T-shirt 1_6",
    Image:
      "https://drive.google.com/file/d/12uak9nHRElhycHmAAJC8Gs5CUnOdYJ4V/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Blue",
    Design: "HypeCulture F* Dip",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Buy the f dip T-shirt 1_5",
    Image:
      "https://drive.google.com/file/d/14sBCYm8rIcBVMi_pGp03x8EO4RdKHF78/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture F* Dip",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Buy the f dip T-shirt 1_4",
    Image:
      "https://drive.google.com/file/d/1e1QPccMCnWd1IHA4myiicL_SDkya0gr4/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Purple",
    Design: "HypeCulture F* Dip",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Buy the f dip T-shirt 1_3",
    Image:
      "https://drive.google.com/file/d/1F9ZExRZces9krHyycX9zjDc2gNWIGIzp/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Green",
    Design: "HypeCulture F* Dip",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Buy the f dip T-shirt 1_1",
    Image:
      "https://drive.google.com/file/d/1kbNBBS2Aa0qP2Dti4HcGY5QClpYoxI8V/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture F* Dip",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Buy the f dip T-shirt",
    Image:
      "https://drive.google.com/file/d/1AaSpG6q30FeDzVs7zHXH56MO2v7XumxS/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture F* Dip",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Buy the f dip T-shirt 1_2",
    Image:
      "https://drive.google.com/file/d/1iKgFO9_vc6xnQb8301fTMjMqEaxKJ8Pu/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture F* Dip",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 0",
    Image:
      "https://drive.google.com/file/d/1oJrsjTTR7LwsQDist84cNXdHhsbvj7wD/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1MquPIs_fD4QpbHVcV6m3cb5nD9ub2hY3/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Gold",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/11OJgoniywyVTT_x0ThF-u20k-jitkImD/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Mint",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/14otVVdnErj7gVgqNwyXtm-0RUU0adQVb/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Light Blue",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 9",
    Image:
      "https://drive.google.com/file/d/1VP9Qhho7f_wah5eTm5MCbOvlxlIIRMtM/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Yellow",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 8",
    Image:
      "https://drive.google.com/file/d/1FogrM4FdlML3lT-1bmONuAOMJft0kSga/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1k8Bj3IYIjY6vXVWPx3kORl0gZxJWRSm8/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Rekt T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/18SRnYuXOnxkkHqDP7VLRUpx7icZIByVk/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Reck",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt 6",
    Image:
      "https://drive.google.com/file/d/1ar71v83bNiJge_UsGbCW06S2GIE9CuE6/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Light Blue",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt 0",
    Image:
      "https://drive.google.com/file/d/1D9Bcpax1O4Az0s4gxjVAwlXntjQKTPC_/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt 7",
    Image:
      "https://drive.google.com/file/d/1uaiH5_UdVmb6ltYO6jVB2rvLs1Ouyz02/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Gold",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1yKy-YhLi1XMeMjKJxdLfwpHZxpNtD7TP/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Mint",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt",
    Image:
      "https://drive.google.com/file/d/1f8_myb00gfDOXAErM9qdq8lVnsTt-Uoe/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/1VmkJKCwgV5_UucqHpxRucdT5wR2ECRPy/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/1ma-WSZ3xV1MNfWJQricPB2isS45nsbYl/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Hodl T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1Mea1PbWR1brEXkfZzDAJr0W6hieXKUuN/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Yellow",
    Design: "HypeCulture Hodl",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt 7",
    Image:
      "https://drive.google.com/file/d/1GVLAdfk4e8x8mglCCgd3eDnNZleOY8FS/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Light Blue",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1tlgj0rACX5m8USDXweQV-D-u54-q7s67/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt",
    Image:
      "https://drive.google.com/file/d/1fH9wjh9iD4TqX3Abm0P7JEMSKX5yWfBI/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Gold",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt 6",
    Image:
      "https://drive.google.com/file/d/1Vo88bei-dWq0x_8BdPOI7pWYlyxuDUWz/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Mint",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/16_ADyRi9Q8FzDie-SV0UH2UkcBmyTBuM/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/1OgmqFmVZ7Nuh8SCUeflDmsmvRK-dQk3n/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/10-0aeurPv7ASF_Ol8o37epf4nn09Wr1O/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Wrecked T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/1dpLgz54uj39zbPCwJnNT0CsY5s5Shl6T/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Yellow",
    Design: "HypeCulture Wrecked",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt 7",
    Image:
      "https://drive.google.com/file/d/1voDqxvWbI2Zpye-xphjDtqIRfyISAAmf/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Light Blue",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1KpvCU5qobqf6gIjfsV9_WkdMOm_WcnqJ/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/1u2-7aaTPiAYOQYSOg7RN4VINOc1KVM3x/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Gold",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt 6",
    Image:
      "https://drive.google.com/file/d/1Gxbxy9Ny996B7p2DtnXevwoEL6gxIUa8/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Mint",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt",
    Image:
      "https://drive.google.com/file/d/146DlyNhiFNzbnhsbvLb-KRSgHVNbSznj/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/1zXG_V5IEIuZIegaA4WgQp9rrtMBCCjvD/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/1_WxvnQuMJ3xZcE2NG6XYvQrtDjWE4IvA/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "White",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Original T-Shirt 0",
    Image:
      "https://drive.google.com/file/d/1qNk4T-YduS4pSWEtkgOCkSgZ4mKtsjfi/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Yellow",
    Design: "HypeCulture Original",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "NFT T-Shirt",
    Image:
      "https://drive.google.com/file/d/1mc60GCHfu2kCDtWRxxIxrAgZ4Z3Pm6wr/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Grey",
    Design: "HypeCulture NFT",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "NFT T-Shirt 1",
    Image:
      "https://drive.google.com/file/d/103DhnGZ5tW1R7Cho-TPMLoZzKp1lpS2M/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Gold",
    Design: "HypeCulture NFT",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "NFT T-Shirt 2",
    Image:
      "https://drive.google.com/file/d/1--lCJSLvxEkpaoZN37o3cG11qkFkRCrw/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Light Blue",
    Design: "HypeCulture NFT",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "NFT T-Shirt 4",
    Image:
      "https://drive.google.com/file/d/1qwDNEu1AkfvdXvA2fWn4qjwvUk2_mcUs/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Mint",
    Design: "HypeCulture NFT",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "NFT T-Shirt 3",
    Image:
      "https://drive.google.com/file/d/1YZWc6dTWbYWbjFWanHi0YJnJI70QMnMn/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture NFT",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "NFT T-Shirt 6",
    Image:
      "https://drive.google.com/file/d/1OcMKQmUbiiXfQyRlMO6pxlQHkLOryqeN/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "White",
    Design: "HypeCulture NFT",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "NFT T-Shirt 5",
    Image:
      "https://drive.google.com/file/d/1fDpACjdEkUr2B2q52-LjYh_7Z3DY3R39/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Yellow",
    Design: "HypeCulture NFT",
    Type: "T-Shirt",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat",
    Image:
      "https://drive.google.com/file/d/1xtfrrrCFzsdV7jkjTu5WmqLqe5e2elAk/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 6",
    Image:
      "https://drive.google.com/file/d/1supeSgJdK74UZ7gTjl9oPWCTSJNZLoyF/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black/White",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 1",
    Image:
      "https://drive.google.com/file/d/1be8oMKj6bIc3MgPy7FWP4VmRnfNlNkUv/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 7",
    Image:
      "https://drive.google.com/file/d/1AhQ9K7j03Rl-OL0StJihzkK8y83UaGmL/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 0",
    Image:
      "https://drive.google.com/file/d/1HKa2xDg722_Phm7s87A90bT8GuyGuuZY/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 5",
    Image:
      "https://drive.google.com/file/d/1Qs1zKItUBlf2-y4CFOqNdTjWTUmva_pZ/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy/White",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 4",
    Image:
      "https://drive.google.com/file/d/10NGKgeQ7mPhgmkqdLCpnq2Xn7xGaQCRG/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 3",
    Image:
      "https://drive.google.com/file/d/1KODaGE4wpL1CnXk55ZicKP-IRwV1q3Ef/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Emblem Hat 2",
    Image:
      "https://drive.google.com/file/d/1wG-wEDZcSqZz9onJjId_TBLzRHeknMyn/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Orange",
    Design: "HypeCulture Emblem",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 0",
    Image:
      "https://drive.google.com/file/d/1AkVFdmSDd3wHnfeJ8zOGhcfHtoOucRIJ/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 8",
    Image:
      "https://drive.google.com/file/d/1qCnuVHpX89yjwOSRVTM0yyktw_HuJCeZ/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black/White",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 7",
    Image:
      "https://drive.google.com/file/d/1gW8ZFxZUB8ENnW2qBTZo0EEjsST5Vx7J/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 6",
    Image:
      "https://drive.google.com/file/d/1zXIdHIz6K4H-sRoZDON5Z2i2HAj_gdR_/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 5",
    Image:
      "https://drive.google.com/file/d/17JCmz30h6g9aBK_MqiDwiycPlht0Pv7K/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 4",
    Image:
      "https://drive.google.com/file/d/1A1SzsqwuCBE9Nnb3NO3wNZWZR59t_df-/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy/White",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 3",
    Image:
      "https://drive.google.com/file/d/1jVdUT8zu5zjbWntVQ4RQPS8_nVW_Bq_r/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 2",
    Image:
      "https://drive.google.com/file/d/1TGIR7tAn19IEMiXCbz6lQOVKD_0WTtOJ/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Original Hat 1",
    Image:
      "https://drive.google.com/file/d/1jKyltjbpz03dhpsKfEoi2XNhQHm-Zlk8/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Orange",
    Design: "HypeCulture Original",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat",
    Image:
      "https://drive.google.com/file/d/1q8zyP88JSzfqR8kYL8jBKxZck-CZUOid/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat 8",
    Image:
      "https://drive.google.com/file/d/1zCW6UkRO0ARxaTVapzQ2NOP9xNXPZK3T/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black/White",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat0",
    Image:
      "https://drive.google.com/file/d/19ORNj6AEK3sxzxlQPS6yHfmZzPRm19tp/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat8",
    Image:
      "https://drive.google.com/file/d/1nixN-0rVS5v0LLaXDnSkRYiSWRkmvAct/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat 6",
    Image:
      "https://drive.google.com/file/d/1ehj54DZzfswfPIEYQaGt5tzJ2hQDST8g/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat 5",
    Image:
      "https://drive.google.com/file/d/1BOS1conuLxeVeGhti-wRjRAZtG9n3wsq/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy/White",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat 4",
    Image:
      "https://drive.google.com/file/d/1ydb8dBYx4ViVjtStayL4jwhEIRmENdRi/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat3",
    Image:
      "https://drive.google.com/file/d/1waN6QncCAJV65s06lcUQumiUi2AGHkRT/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Flower Hat 2",
    Image:
      "https://drive.google.com/file/d/1HEhdzB5rDndTnZhMfdfiCngCI57lzvDw/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Orange",
    Design: "HypeCulture Flower",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat",
    Image:
      "https://drive.google.com/file/d/1YexG4dsgSZmtHfqbIjX0xT9Wypi1rllz/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 8",
    Image:
      "https://drive.google.com/file/d/1C0u31S9ITLn4zLbbyuYQ3nXKNI4NAr8p/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black/White",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 7",
    Image:
      "https://drive.google.com/file/d/1ER-DQ12MuryqQ4-sKi_OhcFuOlLMkJ2-/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 6",
    Image:
      "https://drive.google.com/file/d/1n13nsXYm6cH9RvhqdHFVUc7EgtOjrUjU/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 0",
    Image:
      "https://drive.google.com/file/d/1bUujEhuO8Q1eFAHHnZyTORu3zlNQE16K/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 5",
    Image:
      "https://drive.google.com/file/d/1AHfJKkj5MFahpffIzAXVOzSZb8v3rwYg/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy/White",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 4",
    Image:
      "https://drive.google.com/file/d/1OD7QGRl4d1lH2YX9qTncF3VEpQ-dLG9A/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 2",
    Image:
      "https://drive.google.com/file/d/1JdU9hY4gOzaNH_3ybP-WKxXzBAfAch_U/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Hash Rate Hat 1",
    Image:
      "https://drive.google.com/file/d/1RVOiSu_hHwd2x9aTEiPSuko0fZIhfgqD/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Orange",
    Design: "HypeCulture Hash Rate",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat",
    Image:
      "https://drive.google.com/file/d/18zUrRTxj10ZtLHE4RVcyaAovYjKvAmMd/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 1",
    Image:
      "https://drive.google.com/file/d/1msyH8jkpRtpyEF8Pd0TXXJ0N0y1NtCvl/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Black/White",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 0",
    Image:
      "https://drive.google.com/file/d/1D1yyqqIxeqQXZIaeH6c4b0Hqe8-707sk/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Brown",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 2",
    Image:
      "https://drive.google.com/file/d/1vTxXjnqskPm_AOZHD3IeiHNNLi6ORYKX/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Cream",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 3",
    Image:
      "https://drive.google.com/file/d/13nQt1Oo4XtF19EL1biTRfRtON5D5xWgt/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 4",
    Image:
      "https://drive.google.com/file/d/1148m08Sp70m565BBeFeVwFyWdMEhk-u9/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Navy/White",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 5",
    Image:
      "https://drive.google.com/file/d/1OFebdt5MYgeQndZ7TY6X2NnZ_E9V1k2L/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Pink",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 8",
    Image:
      "https://drive.google.com/file/d/1bgsdPbQYsh9S0fS3eHTqI1FNlsE8iZa5/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Red",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
  {
    Name: "Blockchain Hat 6",
    Image:
      "https://drive.google.com/file/d/1TRlHiSCFxav0vOjJlWwqOlLu6yaggkW-/view?usp=sharing",
    Rarity: "Rare",
    Season: 1,
    Color: "Orange",
    Design: "HypeCulture Blockchain",
    Type: "Hat",
    Quantity: 29,
  },
];
count = 1;
const newMeta = [];
meta.map((nft) => {
  let newImage = ""
  if(["b",  "B" , "c" , "C"].includes( nft.Name[0])  ){
    newImage =   `https://gateway.pinata.cloud/ipfs/bafybeifozoujn4khnpveiglbsliem66co4djhandj5o352qfltzm27jbp4/${nft.Name.replace(/\s+/g, "%20")}.mp4`
   }else if (["d" , "D" , "e" , "E" , "f" , "F" ].includes( nft.Name[0])  ){
     newImage =   `https://gateway.pinata.cloud/ipfs/bafybeid37vgqtnh6q3iczsb6mzdanzjx6j4cvsmcartvgkxbmubum3jepu/${nft.Name.replace(/\s+/g, "%20")}.mp4`
   }else if (["h" , "H"].includes( nft.Name[0])){
     newImage =   `https://gateway.pinata.cloud/ipfs/bafybeibsswnebdpxinpubbn67qr3lxxhyuniadm423rjtwjtthj3iyrfau/${nft.Name.replace(/\s+/g, "%20")}.mp4`
   }else if (["n" , "N" , "o" , "O" , "p" , "P" , "r" , "R" , "s" , "S" , "t" , "T" , , "w" , "W"].includes( nft.Name[0])){
     newImage =   `https://gateway.pinata.cloud/ipfs/bafybeiah3q3hh566f7l2yckc5fkjcdtniyjn5tvve2jl6yhybqktojwf4e/${nft.Name.replace(/\s+/g, "%20")}.mp4`
   }
   if(newImage == ""){
    console.log("iamage Url" , nft.Name )
   }

  for (let index = 0; index < nft.Quantity; index++) {
    newMeta.push({
      name: nft.Name,
      image: newImage,
      properties: {
        rarity: nft.Rarity,
        season: nft.Season,
        color: nft.Color,
        design: nft.Design,
        type: nft.Type,
      },
    });
    count++;
  }
});

for (let index = 0; index < newMeta.length; index++) {
  fs.writeFile(
    `${index + 1}.json`,
    JSON.stringify(newMeta[index]),
    "utf8",
    function (err) {
      if (err) {
        console.log(err);
      } else {
        //Everything went OK!
      }
    }
  );
}
